-- Lists all genres not linked to the show Dexter
SELECT NAME
FROM TV_GENRES
WHERE ID NOT IN (
    SELECT TV_GENRES.ID
    FROM TV_GENRES
    JOIN TV_SHOW_GENRES ON TV_GENRES.ID = TV_SHOW_GENRES.GENRE_ID
    JOIN TV_SHOWS ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
    WHERE TV_SHOWS.TITLE = 'Dexter'
)
ORDER BY NAME;
